-- 코드를 입력하세요
WITH TEMP AS
(
SELECT FOOD_TYPE, REST_ID, REST_NAME, FAVORITES, RANK() OVER (PARTITION BY FOOD_TYPE ORDER BY FAVORITES DESC) RNK
FROM REST_INFO
)
SELECT FOOD_TYPE, REST_ID, REST_NAME, FAVORITES
FROM TEMP
WHERE RNK = 1
ORDER BY FOOD_TYPE DESC