-- 코드를 입력하세요
WITH RECURSIVE CTE(HOUR) AS
(
    SELECT 0
    UNION ALL
    SELECT HOUR + 1
    FROM CTE
    WHERE HOUR < 23
)
SELECT HOUR, COUNT(ANIMAL_ID) COUNT
FROM CTE LEFT JOIN ANIMAL_OUTS ON HOUR = HOUR(DATETIME)
GROUP BY HOUR
ORDER BY HOUR