-- 코드를 입력하세요
WITH temp AS
(
SELECT USER_ID, NICKNAME, SUM(PRICE) TOTAL_SALES
FROM USED_GOODS_BOARD JOIN USED_GOODS_USER ON WRITER_ID = USER_ID AND STATUS = 'DONE'
GROUP BY USER_ID
)
SELECT *
FROM temp
WHERE TOTAL_SALES >= 700000
ORDER BY TOTAL_SALES