-- 코드를 입력하세요
WITH TEMP AS
(
SELECT CAR_ID
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
WHERE YEAR(START_DATE) = 2022 AND MONTH(START_DATE) BETWEEN 8 AND 10
GROUP BY CAR_ID HAVING COUNT(*) >= 5
)
SELECT MONTH(START_DATE) AS MONTH, CAR_ID, COUNT(*) RECORDS
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
WHERE YEAR(START_DATE) = 2022 AND MONTH(START_DATE) BETWEEN 8 AND 10
      AND CAR_ID IN (SELECT * FROM TEMP)
GROUP BY MONTH, CAR_ID
ORDER BY MONTH, CAR_ID DESC