-- 코드를 입력하세요
WITH TEMP AS
(
SELECT CATEGORY, RANK() OVER (PARTITION BY CATEGORY ORDER BY PRICE DESC) RNK, PRICE, PRODUCT_NAME
FROM FOOD_PRODUCT
)
SELECT CATEGORY, PRICE, PRODUCT_NAME
FROM TEMP
WHERE RNK = 1 AND CATEGORY IN ('과자', '국', '김치', '식용유')
ORDER BY PRICE DESC